update

diff --git a/android-emulator/config/bin/wait-for-emulator b/android-emulator/config/bin/wait-for-emulator
--- a/android-emulator/config/bin/wait-for-emulator
+++ b/android-emulator/config/bin/wait-for-emulator
@@ -6,12 +6,12 @@ bootanim=""
 failcounter=0
 until [[ "$bootanim" =~ "stopped" ]]; do
    bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
-   if [[ "$bootanim" =~ "not found" ]]; then
-      let "failcounter += 1"
-      if [[ $failcounter -gt 3 ]]; then
-        echo "  Failed to start emulator"
-        exit 1
-      fi
-   fi
+#   if [[ "$bootanim" =~ "not found" ]]; then
+#      let "failcounter += 1"
+#      if [[ $failcounter -gt 3 ]]; then
+#        echo "  Failed to start emulator"
+#        exit 1
+#      fi
+#   fi
    sleep 1
 done
